[build-system]
requires = [
  "setuptools>=48",
]
build-backend = "setuptools.build_meta"

[project]
name = "vllm-openvino"
description = "OpenVINO plugin for vLLM (patched for v0.19.0)"
readme = "README.md"
license = {text = "Apache 2"}
version = "0.19.0"
dependencies = [
    "openvino >= 2025.1.0",
    "optimum-intel[nncf] @ git+https://github.com/huggingface/optimum-intel.git",
    "vllm >= 0.19.0",
]
requires-python = ">=3.9"

[project.entry-points."vllm.platform_plugins"]
openvino = "vllm_openvino:register"

[tool.setuptools.packages.find]
where = ["."]
include = ["vllm_openvino*"]
exclude = []
namespaces = false
