name: playful_joshua
services:
  main_app:
    cpu_shares: 10
    command:
      - --threads
      - "16"
    container_name: unsloth
    deploy:
      resources:
        limits:
          memory: 270115209216
        reservations:
          devices: []
    environment:
      - JUPYTER_PASSWORD=admin
      - JUPYTER_PORT=8888
      - LLAMA_ARG_THREADS=16
      - USER_PASSWORD=admin
    image: unsloth/unsloth:latest
    labels:
      icon: https://unsloth.ai/cgi/image/unsloth_green_sticker_cME6ryC59BlZg-VtqGN4p.png?width=640&quality=80&format=auto
    ports:
      - target: 8000
        published: "2222"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/Main-Storage/AppData/unsloth/work
        target: /workspace/work
      - type: bind
        source: /media/Main-Storage/AppData/unsloth/home
        target: /home/unsloth
      - type: bind
        source: /media/Main-Storage/AppData/unsloth/.cache
        target: /workspace/.cache
      - type: bind
        source: /media/Main-Storage/AppData/unsloth/studio/outputs
        target: /home/unsloth/studio/outputs
      - type: bind
        source: /media/Main-Storage/AppData/unsloth/studio/exports
        target: /home/unsloth/studio/exports
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://unsloth.ai/cgi/image/unsloth_green_sticker_cME6ryC59BlZg-VtqGN4p.png?width=640&quality=80&format=auto
  index: /
  is_uncontrolled: false
  port_map: "2222"
  scheme: http
  store_app_id: playful_joshua
  title:
    custom: Unsloth Studio
